# remote_theme: pages-themes/midnight@v0.2.0

remote_theme: pages-themes/minimal@v0.2.0
title: ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
description: Amil Shrivastava's CV
pic_link: https://github.com/amil13/Amil-Shrivastava/blob/main/Picture.jpeg
